# Generated by Django 5.2.1 on 2025-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rainfall_mm', models.FloatField()),
            ],
        ),
    ]
